name: MegaRamIncidenciasiOS
options:
  minimumXcodeGenVersion: 2.38.0
configs:
  Debug: debug
  Release: release
targets:
  MegaRamIncidencias:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_NAME: "Incidencias MegaRam"
        PRODUCT_BUNDLE_IDENTIFIER: com.megaram.incidenciasios
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1"
    scheme:
      gatherCoverageData: false
